
  name: CI
  on: [push]
  jobs:
    build:
      runs-on: [self-hosted]
      steps:
        - uses: actions/checkout@v3
        - name: Setup Ruby 3.1
          uses: ruby/setup-ruby@v1
          with: 
            ruby-version: '3.1'
            bundler-cache: true
        - name: SwiftLint
          uses: norio-nomura/action-swiftlint@3.2.1
          with:
            args: --strict
        - name: Build and test
          run: bundle exec fastlane custom_build_and_test
